title: html-indx
description: ' hello_index hello world'
template:
  repo: html-indx-template
  name: html-indx
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
